project:
  type: website
  output-dir: docs
  
website:
  title: "Food Waste"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: references.qmd
        text: References  
      - href: about.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: 
      - /css/styles.css
      - /css/bootstrap.css
    page-layout: custom

editor: visual

